# Generated by Django 5.2.9 on 2025-12-02 14:36

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotel",
            options={
                "ordering": ["name"],
                "verbose_name": "Business",
                "verbose_name_plural": "Businesses",
            },
        ),
        migrations.AddField(
            model_name="hotel",
            name="business_type",
            field=models.CharField(
                choices=[
                    ("HOTEL", "Hotel"),
                    ("RESTAURANT", "Restaurant"),
                    ("CAFE", "Café"),
                    ("CLOUD_KITCHEN", "Cloud Kitchen"),
                ],
                default="HOTEL",
                help_text="The type of food business.",
                max_length=20,
                verbose_name="Business Type",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="enable_room_charging",
            field=models.BooleanField(
                default=False,
                help_text="Allow guests to charge orders to their room (for hotels).",
                verbose_name="Enable Room Charging",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="enable_table_management",
            field=models.BooleanField(
                default=False,
                help_text="Enable table tracking and status (for restaurants).",
                verbose_name="Enable Table Management",
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="enable_waiter_alerts",
            field=models.BooleanField(
                default=False,
                help_text="Allow customers to call waiters (for restaurants).",
                verbose_name="Enable Waiter Alerts",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Card"),
                    ("ROOM_CHARGE", "Charge to Room"),
                    ("ONLINE", "Online Payment"),
                ],
                default="CASH",
                max_length=20,
                verbose_name="Payment Method",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("PARTIAL", "Partially Paid"),
                    ("REFUNDED", "Refunded"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Payment Status",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="special_requests",
            field=models.TextField(
                blank=True,
                help_text="Customer's special requests or notes.",
                verbose_name="Special Requests",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Order subtotal before tax and tip.",
                max_digits=10,
                verbose_name="Subtotal",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tax_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Tax Amount",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tip_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Tip Amount",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="currency_code",
            field=models.CharField(
                help_text="The 3-letter ISO currency code (e.g., USD, EUR, QAR).",
                max_length=3,
                verbose_name="Currency Code",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether the business menu is currently active and accessible.",
                verbose_name="Is Active",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="The business logo image file.",
                null=True,
                upload_to="business_logos/",
                verbose_name="Logo",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="name",
            field=models.CharField(
                help_text="The official name of the business.",
                max_length=255,
                verbose_name="Business Name",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="slug",
            field=models.SlugField(
                help_text="A unique, URL-friendly identifier (e.g., 'bella-italia-doha').",
                max_length=255,
                unique=True,
                verbose_name="Slug",
            ),
        ),
        migrations.AlterField(
            model_name="hotel",
            name="timezone",
            field=models.CharField(
                default="UTC",
                help_text="The timezone for the business (e.g., 'Asia/Qatar').",
                max_length=63,
                verbose_name="Timezone",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="core.hotel",
                verbose_name="Business",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="room_number",
            field=models.CharField(
                help_text="Room number, table number, or location identifier.",
                max_length=50,
                verbose_name="Location",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("ACCEPTED", "Accepted"),
                    ("PREPARING", "Preparing"),
                    ("READY", "Ready"),
                    ("DELIVERED", "Delivered"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="The total price including tax and tip.",
                max_digits=10,
                verbose_name="Total Price",
            ),
        ),
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "table_number",
                    models.CharField(
                        help_text="Table identifier (e.g., '5', 'A1', 'Patio-3').",
                        max_length=50,
                        verbose_name="Table Number",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=4,
                        help_text="Maximum number of guests for this table.",
                        verbose_name="Capacity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("OCCUPIED", "Occupied"),
                            ("RESERVED", "Reserved"),
                            ("CLEANING", "Cleaning"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "qr_code",
                    models.ImageField(
                        blank=True,
                        help_text="Generated QR code for this table.",
                        null=True,
                        upload_to="table_qr_codes/",
                        verbose_name="QR Code",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="core.hotel",
                        verbose_name="Business",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "ordering": ["hotel", "table_number"],
                "unique_together": {("hotel", "table_number")},
            },
        ),
        migrations.AddField(
            model_name="order",
            name="table",
            field=models.ForeignKey(
                blank=True,
                help_text="Associated table (for restaurants).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="core.table",
                verbose_name="Table",
            ),
        ),
        migrations.CreateModel(
            name="WaiterAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("ASSISTANCE", "General Assistance"),
                            ("BILL_REQUEST", "Bill Request"),
                            ("COMPLAINT", "Complaint"),
                            ("REFILL", "Refill Request"),
                        ],
                        default="ASSISTANCE",
                        max_length=20,
                        verbose_name="Alert Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACKNOWLEDGED", "Acknowledged"),
                            ("RESOLVED", "Resolved"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        help_text="Additional details from customer.",
                        verbose_name="Note",
                    ),
                ),
                (
                    "acknowledged_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Acknowledged At"
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Resolved At"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiter_alerts",
                        to="core.hotel",
                        verbose_name="Business",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="waiter_alerts",
                        to="core.table",
                        verbose_name="Table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Waiter Alert",
                "verbose_name_plural": "Waiter Alerts",
                "ordering": ["-created_at"],
            },
        ),
    ]
