# Generated by Django 5.2.9 on 2025-12-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_businessowner"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="allergens",
            field=models.TextField(
                blank=True,
                help_text="Common allergens (e.g., 'Nuts, Dairy, Shellfish').",
                verbose_name="Allergens",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="customization_options",
            field=models.JSONField(
                blank=True,
                help_text="Add-ons, sizes, extras (JSON format).",
                null=True,
                verbose_name="Customization Options",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_daily_special",
            field=models.BooleanField(
                default=False,
                help_text="Mark as today's special offer.",
                verbose_name="Daily Special",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Mark as featured/popular item (chef's recommendation).",
                verbose_name="Featured Item",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="nutritional_info",
            field=models.JSONField(
                blank=True,
                help_text="Calories, protein, carbs, etc. (JSON format).",
                null=True,
                verbose_name="Nutritional Information",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="popularity_score",
            field=models.IntegerField(
                default=0,
                help_text="Auto-incremented when ordered. Higher = more popular.",
                verbose_name="Popularity Score",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="prep_time_minutes",
            field=models.PositiveIntegerField(
                default=15,
                help_text="Estimated preparation time in minutes.",
                verbose_name="Prep Time (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="spice_level",
            field=models.CharField(
                choices=[
                    ("NONE", "No Spice"),
                    ("MILD", "🌶️ Mild"),
                    ("MEDIUM", "🌶️🌶️ Medium"),
                    ("HOT", "🌶️🌶️🌶️ Hot"),
                    ("EXTRA_HOT", "🌶️🌶️🌶️🌶️ Extra Hot"),
                ],
                default="NONE",
                help_text="Spiciness level of the dish.",
                max_length=10,
                verbose_name="Spice Level",
            ),
        ),
    ]
