# Generated by Django 5.2.9 on 2025-12-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_menuitem_allergens_menuitem_customization_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="menu_theme",
            field=models.CharField(
                choices=[("MODERN", "Modern Light"), ("DARK", "Dark Premium")],
                default="MODERN",
                help_text="The visual theme for the customer-facing menu.",
                max_length=20,
                verbose_name="Menu Theme",
            ),
        ),
    ]
