# Generated by Django 5.2.9 on 2025-12-07 13:42

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_menu_theme_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPairFrequency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "times_together",
                    models.IntegerField(
                        default=1,
                        help_text="How many times these items were ordered in the same order.",
                        verbose_name="Times Ordered Together",
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        help_text="P(B|A) - Probability of B being ordered when A is ordered.",
                        verbose_name="Confidence Score",
                    ),
                ),
                (
                    "times_recommended",
                    models.IntegerField(
                        default=0,
                        help_text="How many times this pair was recommended to customers.",
                        verbose_name="Times Recommended",
                    ),
                ),
                (
                    "times_converted",
                    models.IntegerField(
                        default=0,
                        help_text="How many times the recommendation resulted in a purchase.",
                        verbose_name="Times Converted",
                    ),
                ),
                (
                    "revenue_generated",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Total revenue generated from this recommendation pair.",
                        max_digits=10,
                        verbose_name="Revenue Generated",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_pairs",
                        to="core.hotel",
                        verbose_name="Business",
                    ),
                ),
                (
                    "item_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paired_with_a",
                        to="core.menuitem",
                        verbose_name="Item A",
                    ),
                ),
                (
                    "item_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paired_with_b",
                        to="core.menuitem",
                        verbose_name="Item B",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item Pair Frequency",
                "verbose_name_plural": "Item Pair Frequencies",
                "ordering": ["-confidence", "-times_together"],
                "indexes": [
                    models.Index(
                        fields=["hotel", "-confidence"],
                        name="core_itempa_hotel_i_3e0ce6_idx",
                    ),
                    models.Index(
                        fields=["item_a", "-confidence"],
                        name="core_itempa_item_a__4d7e20_idx",
                    ),
                ],
                "unique_together": {("hotel", "item_a", "item_b")},
            },
        ),
        migrations.CreateModel(
            name="RecommendationEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("IMPRESSION", "Shown to Customer"),
                            ("CLICK", "Customer Clicked"),
                            ("CONVERSION", "Customer Purchased"),
                        ],
                        max_length=20,
                        verbose_name="Event Type",
                    ),
                ),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Revenue generated if recommendation converted.",
                        max_digits=10,
                        verbose_name="Revenue",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recommendation_events",
                        to="core.hotel",
                        verbose_name="Business",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        help_text="Order associated with conversion event.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recommendation_events",
                        to="core.order",
                        verbose_name="Order",
                    ),
                ),
                (
                    "recommended_item",
                    models.ForeignKey(
                        help_text="Item that was recommended to the customer.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="was_recommended",
                        to="core.menuitem",
                        verbose_name="Recommended Item",
                    ),
                ),
                (
                    "source_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="Item that triggered the recommendation (e.g., user viewing pizza).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="triggered_recommendations",
                        to="core.menuitem",
                        verbose_name="Source Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommendation Event",
                "verbose_name_plural": "Recommendation Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["hotel", "-created_at"],
                        name="core_recomm_hotel_i_d7c8fc_idx",
                    ),
                    models.Index(
                        fields=["event_type", "-created_at"],
                        name="core_recomm_event_t_86ca0a_idx",
                    ),
                    models.Index(
                        fields=["recommended_item", "event_type"],
                        name="core_recomm_recomme_8ff546_idx",
                    ),
                ],
            },
        ),
    ]
